name: Set secrets as env variables in Github Pages
on: [push, commit]
steps:
  - name: Set Mongo User Name
    env: # Or as an environment variable
      super_secret: ${{ secrets.mongo_user }}
  - name: Set Mongo Password
    env: # Or as an environment variable
      super_secret: ${{ secrets.mongo_password }}